### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by meshula** [nerdvegas/vfxcmake#17]
Hi guys, I wouldn't mind contributing a little to your project. In general, I like to include necessary cmake scripts with my projects, but my projects tend to be licensed under either a modified Apache license, or a simpler BSD or MIT style license. vfxcmake would be an issue then, because the GPL, even the LGPL, turns out to be a show-stopper in every facility I've ever worked at. I was wondering if you've considered possibly dual licensing the project to make participation easier by a broader audience? I realize that the LGPL license would apply only to the build scripts which mitigates, a little, but it would still be an issue if I incorporated one of these Find scripts into one of my projects, and then that became a blocker for a third party wishing in turn to use my project.

**Comment by nerdvegas** [comment]
Personally I would have no issue at all with switching to a BSD/MIT
license. But it's a matter of determining how to do that legally. To my
knowledge this involves getting sign off from all contributors that they
agree for the project to be moved from a less permissive to more permissive
license. It hardly seems much of an issue given the nature of the project,
but you never know.

I've love to hear from someone who knows more about this or has gone
through the process and has suggestions.

Thx
Allan

**Comment by chadrik** [comment]
I also have no issue with switching to BSD or MIT.  

Let's give this a try.  

@nrusch @nyue @caron @drakeguan @dictoon @jhoolmans @sebastianelsner 

All ye contributors to vfxcmake, can switch to an MIT license?  Thanks!

**Comment by dictoon** [comment]
Definitely happy with the MIT license, that's the one we're using for https://github.com/appleseedhq/appleseed.

**Comment by sebastianelsner** [comment]
Good for me!

**Comment by jhoolmans** [comment]
:+1: I have no issue with switching to BSD or MIT.

**Comment by caron** [comment]
Sounds fine to me.

**Comment by nrusch** [comment]
Yeah, fine with me.

**Comment by nyue** [comment]
No problem on my end.

**Comment by meshula** [comment]
Thanks guys!

**Comment by meshula** [comment]
closed as old issue.
